use std::error::Error;

pub fn solve_a(input: &str) -> Result<(), Box<dyn Error>> {
    println!("done a");

    Ok(())
}

pub fn solve_b(input: &str) -> Result<(), Box<dyn Error>> {
    println!("done b");

    Ok(())
}
